import os

PROJECT_ID = os.getenv("PROJECT_ID")
WHATSAPP_TOKEN = os.getenv("WHATSAPP_TOKEN")
WHATSAPP_PHONE_ID = os.getenv("WHATSAPP_PHONE_ID")
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM")
TWILIO_TIMEOUT = int(os.getenv("TWILIO_TIMEOUT", "30"))
INTERNAL_API_TOKEN = os.getenv("INTERNAL_API_TOKEN")
